server:
  port: 8206
spring:
  redis:
    host: ${TENCENT_HOST}
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: ${PASSWORD}}
  rabbitmq:
    host: ${TENCENT_HOST}
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${TENCENT_HOST}:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    username: oreki
    password: ${PASSWORD}}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: service-order
    #热部署配置
  devtools:
    restart:
      enabled: true
      #设置修改文件后需要重启的目录
      additional-paths: src/main/java
      #记住第一个参数的时间要大于第二个参数
      poll-interval: 2s
      quiet-period: 1s
  cloud:
    nacos:
      discovery:
        cluster-name: service-order
        server-addr: ${TENCENT_HOST}:8848
mybatis-plus:
  mapper-locations: classpath:com/oreki/yygh/order/mapper/xml/*
weixin:
  pay:
    appid: wx74862e0dfcf69954
    partner: 1558950191
    partnerKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    certPath: C:\Users\27639\Desktop\java\YiDianTong_parent\service\service-order\src\main\resources\cert\apiclient_cert.p12

##关联的公众号appid
#  weixin.pay.appid=wx74862e0dfcf69954
#  #商户号
#  weixin.pay.partner=1558950191
#  #商户key
#  weixin.pay.partnerKey=T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
