server:
  port: 8202
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.166.210:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: oreki
    password: fqj15823968817
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: service-cmn
    #热部署配置
  devtools:
    restart:
      enabled: true
      #设置修改文件后需要重启的目录
      additional-paths: src/main/java
      #记住第一个参数的时间要大于第二个参数
      poll-interval: 2s
      quiet-period: 1s
  redis:
    host: 39.108.166.210
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: fqj15823968817
  cloud:
    nacos:
      discovery:
        cluster-name: service-cmn
        server-addr: 39.108.166.210:8848
mybatis-plus:
  mapper-locations: classpath:com/oreki/yygh/mapper/xml/*.xml
