server:
  port: 8205
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        cluster-name: service-oss
        server-addr: ${TENCENT_HOST}:8848
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tA2YTNq9cW6jakNQpye
    secret: ${Aliyun_AccessKey_Secret}
    bucket: yidiantong-oreki