server:
  port: 8160
spring:
  redis:
    host: ${TENCENT_HOST}
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: ${PASSWORD}}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${TENCENT_HOST}:3306/yygh_user?characterEncoding=utf-8&useSSL=false
    username: oreki
    password: ${PASSWORD}}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: service-user
    #热部署配置
  devtools:
    restart:
      enabled: true
      #设置修改文件后需要重启的目录
      additional-paths: src/main/java
      #记住第一个参数的时间要大于第二个参数
      poll-interval: 2s
      quiet-period: 1s
  cloud:
    nacos:
      discovery:
        cluster-name: service-user
        server-addr: ${TENCENT_HOST}:8848
mybatis-plus:
  mapper-locations: classpath:com/oreki/yygh/mapper/xml/*.xml
wx:
  open:
    app_id: ${wx_app_id}
    app_secret: ${wx_app_secret}
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
yygh:
  baseUrl: http://localhost:3000

#  wx.open.app_id=wxed9954c01bb89b47
#  wx.open.app_secret=a7482517235173ddb4083788de60b90e
#  wx.open.redirect_url=http://guli.shop/api/ucenter/wx/callback
#  yygh.baseUrl=http://localhost:3000
