server:
  port: 8201
spring:
  redis:
    host: ${TENCENT_HOST}
    port: 6379
    database: 0
    timeout: 1800000
  rabbitmq:
    host: ${TENCENT_HOST}
    port: 5672
    username: guest
    password: guest
  application:
    name: service-hosp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${TENCENT_HOST}:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: oreki
    password: ${PASSWORD}}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #热部署配置
  devtools:
    restart:
      enabled: true
      #设置修改文件后需要重启的目录
      additional-paths: src/main/java
      #记住第一个参数的时间要大于第二个参数
      poll-interval: 2s
      quiet-period: 1s
  data:
    mongodb:
      uri: mongodb://${TENCENT_HOST}:27017/yygh_hosp
  cloud:
    nacos:
      discovery:
        server-addr: ${TENCENT_HOST}:8848
        cluster-name: service-hosp
mybatis-plus:
  mapper-locations: classpath:com/oreki/yygh/mapper/xml/*.xml


