server:
  port: 80
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.166.210:8848
        cluster-name: service-gateway
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:   # 允许哪些网站的跨域请求 allowedOrigins: “*” 允许所有网站
              - "http://localhost:9528"
            allowedMethods:   # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**